name: gmgn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  solana: ^0.32.0
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  flutter_riverpod: ^2.5.0
  pointycastle: ^3.7.3
  intl: ^0.19.0
  clipboard: ^0.1.3
  go_router: ^14.4.0
  fl_chart: ^0.66.0
  webview_flutter: ^4.7.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env